# Generated by Django 4.2.13 on 2024-06-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('characters', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashstring', models.CharField(max_length=65536)),
                ('cracked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hashcat_module', models.IntegerField()),
            ],
            options={
                'ordering': ['hashcat_module'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('characters', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashes', models.ManyToManyField(to='zebra.hash')),
            ],
        ),
        migrations.AddField(
            model_name='hash',
            name='hashtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zebra.hashtype'),
        ),
        migrations.AddField(
            model_name='hash',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zebra.project'),
        ),
    ]
