# Generated by Django 4.2.13 on 2024-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='comment',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=8192),
            preserve_default=False,
        ),
    ]
