# Generated by Django 4.2.13 on 2024-06-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0002_hash_comment_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='comment',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
