# Generated by Django 4.2.13 on 2024-06-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0003_alter_hash_comment_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterset',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hashtype',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='wildcard',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='wildcard',
            name='parent_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='zebra.characterset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hashtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
