# Generated by Django 4.2.13 on 2026-08-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0004_characterset_comment_hashtype_comment_run_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='universe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='attack_mode',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='run',
            name='command',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='hashtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zebra.hashtype'),
        ),
        migrations.AddField(
            model_name='run',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='run',
            name='speed_hs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('exhausted', 'Exhausted'), ('aborted', 'Aborted'), ('cracked', 'Cracked'), ('error', 'Error')], default='planned', max_length=16),
        ),
        migrations.AlterField(
            model_name='hash',
            name='cracked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=1024)),
                ('custom_charsets', models.JSONField(blank=True, default=dict)),
                ('length', models.IntegerField(default=0)),
                ('keyspace', models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='zebra.project')),
            ],
            options={
                'ordering': ['length', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='Crack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.CharField(max_length=1024)),
                ('found_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cracks', to='zebra.hash')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cracks', to='zebra.run')),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200)),
                ('speed_hs', models.DecimalField(decimal_places=0, max_digits=80)),
                ('measured_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='zebra.hashtype')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='zebra.mask'),
        ),
    ]
