# Generated by Django 6.1 on 2026-08-21 08:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_run_project(apps, schema_editor):
    """Existing runs were linked to a project only through their mask; copy that
    onto the new direct Run.project FK so non-mask runs can share the relation."""
    Run = apps.get_model('zebra', 'Run')
    for run in Run.objects.filter(project__isnull=True, mask__isnull=False):
        run.project_id = run.mask.project_id
        run.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0006_seed_hashtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('path', models.CharField(blank=True, max_length=1024, null=True)),
                ('rule_count', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('path', models.CharField(blank=True, max_length=1024, null=True)),
                ('line_count', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='run',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='zebra.project'),
        ),
        migrations.AddField(
            model_name='run',
            name='signature',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='run',
            name='attack_mode',
            field=models.IntegerField(choices=[(0, 'Straight'), (1, 'Combinator'), (3, 'Mask'), (6, 'Hybrid WL+Mask'), (7, 'Hybrid Mask+WL')], default=3),
        ),
        migrations.AddField(
            model_name='run',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='runs', to='zebra.ruleset'),
        ),
        migrations.AddField(
            model_name='run',
            name='wordlists',
            field=models.ManyToManyField(blank=True, related_name='runs', to='zebra.wordlist'),
        ),
        migrations.RunPython(backfill_run_project, migrations.RunPython.noop),
    ]
