# Generated by Django 6.1 on 2026-08-21 10:01
import django.db.models.deletion
from django.db import migrations, models


def backfill_project_hashtype(apps, schema_editor):
    """Set each project's hashtype from its hashes before the per-hash field is
    dropped. A project targets one type now; warn about any that currently hold
    more than one (those should be split into separate projects)."""
    from collections import Counter
    Project = apps.get_model('zebra', 'Project')
    Hash = apps.get_model('zebra', 'Hash')
    for project in Project.objects.all():
        counts = Counter(
            Hash.objects.filter(project=project).values_list('hashtype_id', flat=True))
        counts.pop(None, None)
        if not counts:
            continue
        if len(counts) > 1:
            print('  WARNING: project %r (id=%s) has %d hash types %s -- assigned the '
                  'most common; split it into one project per type.'
                  % (project.name, project.pk, len(counts), list(counts)))
        project.hashtype_id = counts.most_common(1)[0][0]
        project.save(update_fields=['hashtype'])


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0007_ruleset_wordlist_run_params_run_project_and_more'),
    ]

    operations = [
        # 1. Add the new project-level field (nullable for now).
        migrations.AddField(
            model_name='project',
            name='hashtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='zebra.hashtype'),
        ),
        # 2. Backfill it from the per-hash type (still present at this point).
        migrations.RunPython(backfill_project_hashtype, migrations.RunPython.noop),
        # 3. Drop the now-redundant per-hash / per-run types.
        migrations.RemoveField(
            model_name='hash',
            name='hashtype',
        ),
        migrations.RemoveField(
            model_name='run',
            name='hashtype',
        ),
    ]
