# Generated by Django 6.1 on 2026-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0008_remove_hash_hashtype_remove_run_hashtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
