# Generated by Django 6.1 on 2026-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0010_project_benchmark_hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='increment_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mask',
            name='increment_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
