# Generated by Django 6.1 on 2026-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0011_mask_increment_max_mask_increment_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='increment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='increment_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
