# Generated by Django 6.1 on 2026-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0012_run_increment_count_run_increment_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='queue_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('queued', 'Queued'), ('running', 'Running'), ('exhausted', 'Exhausted'), ('aborted', 'Aborted'), ('cracked', 'Cracked'), ('error', 'Error')], default='planned', max_length=16),
        ),
    ]
