# Generated by Django 6.1 on 2026-09-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0011_settings'),
        ('zebra', '0013_run_queue_position_alter_run_status'),
    ]

    operations = [
    ]
