# Generated by Django 6.1 on 2026-09-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0014_merge_20260923_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hash_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hashfile_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='hashfile_path',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='potfile_path',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
