# Generated by Django 6.1 on 2026-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0015_project_hash_count_project_hashfile_managed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='recovered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
