# Generated by Django 6.1 on 2026-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0016_run_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='optimized',
            field=models.BooleanField(default=True),
        ),
    ]
