# Generated by Django 6.1 on 2026-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0017_run_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='crack_baseline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
