# Generated by Django 6.1 on 2026-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0018_run_crack_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='crack_range_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
