# Generated by Django 6.1 on 2026-09-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0019_run_crack_range_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='queue_paused',
            field=models.BooleanField(default=False),
        ),
    ]
