# Generated by Django 6.1 on 2026-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0020_settings_queue_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='queue_paused',
        ),
        migrations.AddField(
            model_name='settings',
            name='auto_task_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='settings',
            name='queue_mode',
            field=models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('auto', 'Auto')], default='on', max_length=4),
        ),
    ]
