# Generated by Django 6.1 on 2026-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0021_remove_settings_queue_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='potfile_path',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='run',
            name='restore_path',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='run',
            name='session',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
