# Generated by Django 6.1 on 2026-09-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0023_alter_benchmark_speed_hs_alter_mask_keyspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coverage_cache',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
